import { Plus_Jakarta_Sans } from 'next/font/google';

import Cursor from '@/components/Cursor';
import SmoothScroll from '@/components/SmoothScroll';
import SocialLinks from '@/components/SocialLinks';
import CursorProvider from '@/providers/CursorProvider';
import ThemeProvider from '@/providers/ThemeProvider';

import './globals.css';

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-jakarta'
});

export const metadata = {
  title: 'Mostofa Nobi',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${jakarta.variable} bg-dark font-jakarta text-dark`}
      >
        <SmoothScroll>
          <ThemeProvider>
            <CursorProvider>
              {children}
              {/* <SocialLinks /> */}
              <Cursor />
            </CursorProvider>
          </ThemeProvider>
        </SmoothScroll>
      </body>
    </html>
  );
}
